# Site settings
title: 김끄덕
description: Jekyll Theme Minimal Resume
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://SummerPlumage.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: 김끄덕
user_description: HI
user_title: Developer
email: ""
# twitter_username: lorem_ipsum
github_username:  roptibug
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
